ci: use miniconda

diff --git a/.github/workflows/ci-test-bump-dev.yml b/.github/workflows/ci-test-bump-dev.yml
--- a/.github/workflows/ci-test-bump-dev.yml
+++ b/.github/workflows/ci-test-bump-dev.yml
@@ -34,7 +34,14 @@ jobs:
     name: Bump dev version & build dev package
     runs-on: ubuntu-latest
     environment: dev
+    defaults:
+      run:
+        shell: bash -el {0}
     steps:
+    - uses: conda-incubator/setup-miniconda@v3
+      with:
+        miniconda-version: "latest"
+        activate-environment: ""  # not creating a build env at present
     - name: Retrieve the source code
       uses: actions/checkout@v4
       with:
@@ -43,110 +50,126 @@ jobs:
       id: config_tools
       run: |
         # simpler to use pip - couldn't figure out how to use conda env
-        pip install commitizen
         git config --global user.email "you@example.com"
         git config --global user.name "PR-bot"
-    - name: get short git hash; install commitizen
-      id: get_version
-      run: |
-        set -euxo pipefail
-        echo "SHORT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
-      shell: bash
-#    - name: Debug
-#      if: ${{ github.event.inputs.debug == 'true' }}
-#      env:
-#        VERSION: ${{ steps.get_version.outputs.SHORT_HASH }}
-#        PR_URL: https://github.com/${{ github.repository }}/pull/${{ github.event.number }}
-#        PRNUM: PR#${{ github.event.number }}
-#        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-#        GH_CONTEXT: ${{ toJson(github) }}
-#      uses: mxschmitt/action-tmate@v3
-    - name: Create PR
-      env:
-        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        EVENT: ${{ github.event_name }}
-        BRANCH_PRE: test-dev-build-${{ steps.get_version.outputs.SHORT_HASH }}
-        VERSION: ${{ steps.get_version.outputs.SHORT_HASH}}
-      run: |
-        set -euxo pipefail
-        PRE_TITLE="[${VERSION}]Dev vers bump:"
-        if [[ "$EVENT" == "workflow_dispatch" ]]; then
-          BRANCH=$BRANCH_PRE/workflow_dispatch
-          TITLE="${PRE_TITLE} triggered manually"
-          BODY="- Created by manual trigger"
-        else
-          PR=${{ github.event.number }}
-          REPO=${{ github.repository }}
-          BRANCH=$BRANCH_PRE/${{ github.head_ref }}
-          TITLE="[${PRE_TITLE}] triggered by updates from PR: ${PR}"
-          BODY="- Created after merging [PR#${PR}](https://github.com/${REPO}/pull/${PR})"
-        fi
 
-        git checkout -b $BRANCH
+        conda config --add channels conda-forge
 
-        echo "bump dev version (do not push tag)"
-        cz bump --yes $(cz bump --yes --get-next)+${VERSION}
+        # install & configure conda packages
+        conda install -y commitizen
+        conda install -y conda-build conda-repo-cli
 
-        if ${{ github.event.inputs.open_pr == 'true' }}; then
-          echo "Open a PR for ${BRANCH}"
-          git push -u origin $BRANCH
-          gh pr create -B main --title "$TITLE" --body "$BODY"
-        fi
-      shell: bash
-    - name: build package
-      id: build
-      run: |
-        echo "current branch: $(git rev-parse --abbrev-ref HEAD)"
-        conda install -y conda-build
-        # couldn't get a build when using --output
-        conda build conda.recipe/
-        CONDA_FILE=$(find ${CONDA}/conda-bld -type f -name "test*.conda")
-        echo "CONDA_PACKAGE=$CONDA_FILE" >> $GITHUB_ENV
-      shell: bash
-    - name: Upload package
-      env:
-        PSM: anacondaconnect
-        PSM_URL: https://pkgs.as.anacondaconnect.com
-        TOKEN: ${{ secrets.PSM_TEST_UPLOAD_TOKEN }}
-      run: |
-        set -euxo pipefail
-        export CONDA_PREFIX=${CONDA}
-        conda install conda-repo-cli
-        conda repo config --set sites.${PSM}.url ${PSM_URL}/api
-        ## following fails since it needs cf headers; commented here.
-        #conda repo --verbose --token ${TOKEN} \
-        #--site ${PSM} \
-        #upload \
-        #--channel ai-aug/dev \
-        #${{ env.CONDA_PACKAGE }}
-      shell: bash
+        echo "CONDA_PREFIX - ${CONDA_PREFIX}"
+        cz version
     - name: Debug
       env:
         PSM: anacondaconnect
         PSM_URL: https://pkgs.as.anacondaconnect.com
         TOKEN: ${{ secrets.PSM_TEST_UPLOAD_TOKEN }}
-      if: ${{ github.event.inputs.debug == 'true' }}
+      if: ${{ github.event.inputs.debug == 'true' || failure() }}
       uses: mxschmitt/action-tmate@v3
-    - name: 'Upload Artifact'
-      uses: actions/upload-artifact@v4
-      with:
-        name: test
-        path: ${{ env.CONDA_PACKAGE }}
-        retention-days: 7
-
-    #  if: false
-    #  id: cpr
-    #  uses: peter-evans/create-pull-request@v7
-    #  with:
-    #    # context is for creating a PR where base is main.
-    #    #   github.head_ref - name of the branch that has been merged
-    #    #   github.event.number - # of the PR that was just merged
-    #    token: ${{ secrets.TEST_TOKEN }}
-    #    branch: update-agent-api-wrapper/${{ github.head_ref }}
-    #    title: Build spec update from PR#${{ github.event.number }}
-    #    body: |
-    #      - Created upon merge of: [PR#${{ github.event.number }}](https://github.com/${{ github.event.repository }}/pull/${{ github.event.number }})
-    #      - Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action
-    #    labels: |
-    #      automation
-    #      ${{ github.ref_name }}
+## Stop here for now
+##    - name: get short git hash; install commitizen
+##      id: get_version
+##      run: |
+##        set -euxo pipefail
+##        echo "SHORT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
+##      shell: bash
+###    - name: Debug
+###      if: ${{ github.event.inputs.debug == 'true' }}
+###      env:
+###        VERSION: ${{ steps.get_version.outputs.SHORT_HASH }}
+###        PR_URL: https://github.com/${{ github.repository }}/pull/${{ github.event.number }}
+###        PRNUM: PR#${{ github.event.number }}
+###        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+###        GH_CONTEXT: ${{ toJson(github) }}
+###      uses: mxschmitt/action-tmate@v3
+##    - name: Create PR
+##      env:
+##        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+##        EVENT: ${{ github.event_name }}
+##        BRANCH_PRE: test-dev-build-${{ steps.get_version.outputs.SHORT_HASH }}
+##        VERSION: ${{ steps.get_version.outputs.SHORT_HASH}}
+##      run: |
+##        set -euxo pipefail
+##        PRE_TITLE="[${VERSION}]Dev vers bump:"
+##        if [[ "$EVENT" == "workflow_dispatch" ]]; then
+##          BRANCH=$BRANCH_PRE/workflow_dispatch
+##          TITLE="${PRE_TITLE} triggered manually"
+##          BODY="- Created by manual trigger"
+##        else
+##          PR=${{ github.event.number }}
+##          REPO=${{ github.repository }}
+##          BRANCH=$BRANCH_PRE/${{ github.head_ref }}
+##          TITLE="[${PRE_TITLE}] triggered by updates from PR: ${PR}"
+##          BODY="- Created after merging [PR#${PR}](https://github.com/${REPO}/pull/${PR})"
+##        fi
+##
+##        git checkout -b $BRANCH
+##
+##        echo "bump dev version (do not push tag)"
+##        cz bump --yes $(cz bump --yes --get-next)+${VERSION}
+##
+##        if ${{ github.event.inputs.open_pr == 'true' }}; then
+##          echo "Open a PR for ${BRANCH}"
+##          git push -u origin $BRANCH
+##          gh pr create -B main --title "$TITLE" --body "$BODY"
+##        fi
+##      shell: bash
+##    - name: build package
+##      id: build
+##      run: |
+##        echo "current branch: $(git rev-parse --abbrev-ref HEAD)"
+##        conda install -y conda-build
+##        # couldn't get a build when using --output
+##        conda build conda.recipe/
+##        CONDA_FILE=$(find ${CONDA}/conda-bld -type f -name "test*.conda")
+##        echo "CONDA_PACKAGE=$CONDA_FILE" >> $GITHUB_ENV
+##      shell: bash
+##    - name: Upload package
+##      env:
+##        PSM: anacondaconnect
+##        PSM_URL: https://pkgs.as.anacondaconnect.com
+##        TOKEN: ${{ secrets.PSM_TEST_UPLOAD_TOKEN }}
+##      run: |
+##        set -euxo pipefail
+##        conda install conda-repo-cli
+##        conda repo config --set sites.${PSM}.url ${PSM_URL}/api
+##        ## following fails since it needs cf headers; commented here.
+##        #conda repo --verbose --token ${TOKEN} \
+##        #--site ${PSM} \
+##        #upload \
+##        #--channel ai-aug/dev \
+##        #${{ env.CONDA_PACKAGE }}
+##      shell: bash
+##    - name: Debug
+##      env:
+##        PSM: anacondaconnect
+##        PSM_URL: https://pkgs.as.anacondaconnect.com
+##        TOKEN: ${{ secrets.PSM_TEST_UPLOAD_TOKEN }}
+##      if: ${{ github.event.inputs.debug == 'true' }}
+##      uses: mxschmitt/action-tmate@v3
+##    - name: 'Upload Artifact'
+##      uses: actions/upload-artifact@v4
+##      with:
+##        name: test
+##        path: ${{ env.CONDA_PACKAGE }}
+##        retention-days: 7
+##
+##    #  if: false
+##    #  id: cpr
+##    #  uses: peter-evans/create-pull-request@v7
+##    #  with:
+##    #    # context is for creating a PR where base is main.
+##    #    #   github.head_ref - name of the branch that has been merged
+##    #    #   github.event.number - # of the PR that was just merged
+##    #    token: ${{ secrets.TEST_TOKEN }}
+##    #    branch: update-agent-api-wrapper/${{ github.head_ref }}
+##    #    title: Build spec update from PR#${{ github.event.number }}
+##    #    body: |
+##    #      - Created upon merge of: [PR#${{ github.event.number }}](https://github.com/${{ github.event.repository }}/pull/${{ github.event.number }})
+##    #      - Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action
+##    #    labels: |
+##    #      automation
+##    #      ${{ github.ref_name }}
+##
